services:
  # --- Weaviate Database ---
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate_db
    ports:
      - "8080:8080"    # HTTP API

    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      # Отключаем встроенную векторизацию (ее делает DeepFace)
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      PERSISTENCE_DATA_PATH: './data'
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  api:
    container_name: fastapi
    build:
        context: ./fastapi
        dockerfile: Dockerfile
    working_dir: /app
    ports:
        - "8000:8000"

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

volumes:
  weaviate_data: