services:
  weaviate_db:
    image: semitechnologies/weaviate:latest
    container_name: weaviate_db
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  api:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      # Ссылаемся на имя сервиса weaviate_db
      - DEEPFACE_CONNECTION_DETAILS=http://weaviate_db:8080
    volumes:
      - ~/.deepface/weights:/root/.deepface/weights
    depends_on:
      - weaviate_db
    restart: unless-stopped

volumes:
  weaviate_data: